name: "drv1"

services:
  server:
    #    image: app-drv1-node:latest
    build:
      context: ./docker/node
      args:
        - UID=1000
        - GID=1000
        - USER_NAME=dev
    user: 1000:1000
    volumes:
      - ./source:/app
    ports:
      - 3001:3001
    working_dir: /app/server
    command:
      - npm
      - run
      - watch

  client:
    #    image: app-drv1-node:latest
    build:
      context: ./docker/node
      args:
        - UID=1000
        - GID=1000
        - USER_NAME=dev
    user: 1000:1000
    volumes:
      - ./source/client:/app
    ports:
      - 3000:3000
    command:
      - npm
      - run
      - dev
